### PR TITLE
COMP: Address ITK Windows warnings

### PR DESCRIPTION
**Pull request by thewtex**
Bumps to CI to HEAD of current ITK `release` branch to incorporate:

- https://github.com/InsightSoftwareConsortium/ITK/commit/0892cd1e3f314efb2a1d92490352b891b88100eb

to address related Windows CI warnings such as:

```
\d\a\ITKTubeTK\ITKTubeTK\Modules\Core\Common\src\itkNumericTraits.cxx(76): warning C4996: 'std::complex<char>::complex': warning STL4037: The effect of instantiating the template std::complex for any type other than float, double, or long double is unspecified. You can define _SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING to suppress this warning.
```

### CODE REVIEW

**Comment by thewtex** [comment]
To :green_apple: we go!

**Comment by aylward** [comment]
Re-running failed tests...but it looks like the warnings persist.

**Comment by thewtex** [comment]
I think we have to also enable `ITK_LEGACY_REMOVE`. Trying it...

**Review by aylward — APPROVED** [review]
LGTM!

Failing test is not related to this commit and is being fixed in a separate pull request.

**Pull request merged**
